// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/all/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/all">> = Specific
  const handler = {} as typeof import("../../../src/app/all/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/cards/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cards/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/cards/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/embed/[projectId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/embed/[projectId]">> = Specific
  const handler = {} as typeof import("../../../src/app/embed/[projectId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/embed/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/embed">> = Specific
  const handler = {} as typeof import("../../../src/app/embed/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/p/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/p/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/p/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/automations/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/automations/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/automations/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/automations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/automations">> = Specific
  const handler = {} as typeof import("../../../src/app/api/automations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/board-path/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/board-path">> = Specific
  const handler = {} as typeof import("../../../src/app/api/board-path/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/calendar/parse/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/calendar/parse">> = Specific
  const handler = {} as typeof import("../../../src/app/api/calendar/parse/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/cards/[id]/agent-history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cards/[id]/agent-history">> = Specific
  const handler = {} as typeof import("../../../src/app/api/cards/[id]/agent-history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/cards/[id]/agent-message/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cards/[id]/agent-message">> = Specific
  const handler = {} as typeof import("../../../src/app/api/cards/[id]/agent-message/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/cards/[id]/archive/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cards/[id]/archive">> = Specific
  const handler = {} as typeof import("../../../src/app/api/cards/[id]/archive/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/cards/[id]/contacts/[contactCardId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cards/[id]/contacts/[contactCardId]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/cards/[id]/contacts/[contactCardId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/cards/[id]/contacts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cards/[id]/contacts">> = Specific
  const handler = {} as typeof import("../../../src/app/api/cards/[id]/contacts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/cards/[id]/dependencies/[depId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cards/[id]/dependencies/[depId]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/cards/[id]/dependencies/[depId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/cards/[id]/dependencies/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cards/[id]/dependencies">> = Specific
  const handler = {} as typeof import("../../../src/app/api/cards/[id]/dependencies/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/cards/[id]/files/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cards/[id]/files">> = Specific
  const handler = {} as typeof import("../../../src/app/api/cards/[id]/files/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/cards/[id]/git/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cards/[id]/git">> = Specific
  const handler = {} as typeof import("../../../src/app/api/cards/[id]/git/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/cards/[id]/iterate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cards/[id]/iterate">> = Specific
  const handler = {} as typeof import("../../../src/app/api/cards/[id]/iterate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/cards/[id]/iterations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cards/[id]/iterations">> = Specific
  const handler = {} as typeof import("../../../src/app/api/cards/[id]/iterations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/cards/[id]/kill-agent/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cards/[id]/kill-agent">> = Specific
  const handler = {} as typeof import("../../../src/app/api/cards/[id]/kill-agent/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/cards/[id]/move/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cards/[id]/move">> = Specific
  const handler = {} as typeof import("../../../src/app/api/cards/[id]/move/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/cards/[id]/reset/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cards/[id]/reset">> = Specific
  const handler = {} as typeof import("../../../src/app/api/cards/[id]/reset/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/cards/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cards/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/cards/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/cards/[id]/steer/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cards/[id]/steer">> = Specific
  const handler = {} as typeof import("../../../src/app/api/cards/[id]/steer/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/cards/[id]/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cards/[id]/upload">> = Specific
  const handler = {} as typeof import("../../../src/app/api/cards/[id]/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/cards/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cards">> = Specific
  const handler = {} as typeof import("../../../src/app/api/cards/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/chat/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/chat/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/chat/[id]/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat/[id]/upload">> = Specific
  const handler = {} as typeof import("../../../src/app/api/chat/[id]/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat">> = Specific
  const handler = {} as typeof import("../../../src/app/api/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/claude-auth/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/claude-auth">> = Specific
  const handler = {} as typeof import("../../../src/app/api/claude-auth/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/contacts/[id]/email/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contacts/[id]/email">> = Specific
  const handler = {} as typeof import("../../../src/app/api/contacts/[id]/email/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/contacts/[id]/emails/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contacts/[id]/emails">> = Specific
  const handler = {} as typeof import("../../../src/app/api/contacts/[id]/emails/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/contacts/[id]/memories/[memId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contacts/[id]/memories/[memId]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/contacts/[id]/memories/[memId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/contacts/[id]/memories/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contacts/[id]/memories">> = Specific
  const handler = {} as typeof import("../../../src/app/api/contacts/[id]/memories/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/contacts/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contacts/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/contacts/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/contacts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contacts">> = Specific
  const handler = {} as typeof import("../../../src/app/api/contacts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/email-inbound/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/email-inbound">> = Specific
  const handler = {} as typeof import("../../../src/app/api/email-inbound/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/emails/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/emails/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/emails/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/emails/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/emails">> = Specific
  const handler = {} as typeof import("../../../src/app/api/emails/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/emails/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/emails/sync">> = Specific
  const handler = {} as typeof import("../../../src/app/api/emails/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/file/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/file">> = Specific
  const handler = {} as typeof import("../../../src/app/api/file/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/git-tags/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/git-tags">> = Specific
  const handler = {} as typeof import("../../../src/app/api/git-tags/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/graph/[id]/neighbors/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/graph/[id]/neighbors">> = Specific
  const handler = {} as typeof import("../../../src/app/api/graph/[id]/neighbors/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/graph/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/graph/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/graph/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/graph/relations/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/graph/relations/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/graph/relations/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/graph/relations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/graph/relations">> = Specific
  const handler = {} as typeof import("../../../src/app/api/graph/relations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/graph/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/graph">> = Specific
  const handler = {} as typeof import("../../../src/app/api/graph/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/graph/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/graph/search">> = Specific
  const handler = {} as typeof import("../../../src/app/api/graph/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/integrations/support/ingest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations/support/ingest">> = Specific
  const handler = {} as typeof import("../../../src/app/api/integrations/support/ingest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/integrations/support/routing/[index]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations/support/routing/[index]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/integrations/support/routing/[index]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/integrations/support/routing/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations/support/routing">> = Specific
  const handler = {} as typeof import("../../../src/app/api/integrations/support/routing/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/iterations/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/iterations/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/iterations/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/knowledge/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/knowledge">> = Specific
  const handler = {} as typeof import("../../../src/app/api/knowledge/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/knowledge/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/knowledge/search">> = Specific
  const handler = {} as typeof import("../../../src/app/api/knowledge/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/media/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/media">> = Specific
  const handler = {} as typeof import("../../../src/app/api/media/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/memory/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/memory">> = Specific
  const handler = {} as typeof import("../../../src/app/api/memory/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/notify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notify">> = Specific
  const handler = {} as typeof import("../../../src/app/api/notify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/og/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/og">> = Specific
  const handler = {} as typeof import("../../../src/app/api/og/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/projects/[id]/cards/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/cards">> = Specific
  const handler = {} as typeof import("../../../src/app/api/projects/[id]/cards/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/projects/[id]/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/chat">> = Specific
  const handler = {} as typeof import("../../../src/app/api/projects/[id]/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/projects/[id]/column-config/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/column-config">> = Specific
  const handler = {} as typeof import("../../../src/app/api/projects/[id]/column-config/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/projects/[id]/detect-version/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/detect-version">> = Specific
  const handler = {} as typeof import("../../../src/app/api/projects/[id]/detect-version/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/projects/[id]/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/export">> = Specific
  const handler = {} as typeof import("../../../src/app/api/projects/[id]/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/projects/[id]/files/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/files">> = Specific
  const handler = {} as typeof import("../../../src/app/api/projects/[id]/files/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/projects/[id]/git/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/git">> = Specific
  const handler = {} as typeof import("../../../src/app/api/projects/[id]/git/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/projects/[id]/import/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/import">> = Specific
  const handler = {} as typeof import("../../../src/app/api/projects/[id]/import/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/projects/[id]/meta/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/meta">> = Specific
  const handler = {} as typeof import("../../../src/app/api/projects/[id]/meta/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/projects/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/projects/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/projects/[id]/start/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/start">> = Specific
  const handler = {} as typeof import("../../../src/app/api/projects/[id]/start/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/projects/[id]/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/status">> = Specific
  const handler = {} as typeof import("../../../src/app/api/projects/[id]/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/projects/[id]/versions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/versions">> = Specific
  const handler = {} as typeof import("../../../src/app/api/projects/[id]/versions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/projects/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects">> = Specific
  const handler = {} as typeof import("../../../src/app/api/projects/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/provider-auth/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/provider-auth">> = Specific
  const handler = {} as typeof import("../../../src/app/api/provider-auth/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/reflection/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reflection">> = Specific
  const handler = {} as typeof import("../../../src/app/api/reflection/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/report/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/report">> = Specific
  const handler = {} as typeof import("../../../src/app/api/report/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/search">> = Specific
  const handler = {} as typeof import("../../../src/app/api/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings">> = Specific
  const handler = {} as typeof import("../../../src/app/api/settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/team/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/team/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/team/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/team/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/team">> = Specific
  const handler = {} as typeof import("../../../src/app/api/team/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/templates/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/templates">> = Specific
  const handler = {} as typeof import("../../../src/app/api/templates/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/vault/check/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vault/check">> = Specific
  const handler = {} as typeof import("../../../src/app/api/vault/check/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/vault/get/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vault/get">> = Specific
  const handler = {} as typeof import("../../../src/app/api/vault/get/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/vault/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vault">> = Specific
  const handler = {} as typeof import("../../../src/app/api/vault/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/version/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/version">> = Specific
  const handler = {} as typeof import("../../../src/app/api/version/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/ws/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ws">> = Specific
  const handler = {} as typeof import("../../../src/app/api/ws/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/uploads/[...filename]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/uploads/[...filename]">> = Specific
  const handler = {} as typeof import("../../../src/app/uploads/[...filename]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
